# Generated by Django 5.0.2 on 2025-04-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='devolvido',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('emprestado', 'Emprestado'), ('devolvido', 'Devolvido'), ('atrasado', 'Atrasado')], default='emprestado', max_length=20),
        ),
    ]
